### ISSUE TITLE
Possible cdn install ?

### ISSUE THREAD

**Issue by Songoo7** [parsajiravand/vue-client-recaptcha#5]
Hello, I tried to do inline install , is that possible ?

I tried it like this:

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/vue-client-recaptcha.umd.js"></script>
<link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/style.css">

                             <div class="capcha-wrapper" id="register-capcha">
                                        <input type="text" v-model="inputValue" />
                                        <supercapch
                                        :value="inputValue"
                                        @getCode="getCaptchaCode"
                                        @isValid="checkValidCaptcha"
                                        />
                                </div>

    <script type="application/javascript">
            const registerCapcha = {
                data: function() {
                    return {}
                },
                methods: {},
                components: {
                    "supercapch": VueClientRecaptcha
                },
                setup() {
                    var inputValue = null;

                    var getCaptchaCode = function getCaptchaCode(value) {
                        console.log(value);
                    };
                    var checkValidCaptcha = function checkValidCaptcha(value) {
                        console.log(value);
                    };
                    return {
                        inputValue,
                        getCaptchaCode,
                        checkValidCaptcha,
                    };
                }
            };
            Vue.createApp(registerCapcha).use(store).mount('#register-capcha');
    </script>
```

Which sadly ends up with ": e.useSlots is not a function" error, couldnt find any example on how to get it working in this way, using vue3

**Comment by parsajiravand** [comment]
> Hello, I tried to do inline install , is that possible ?
> 
> I tried it like this:
> 
> ```
> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/vue-client-recaptcha.umd.js"></script>
> <link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/style.css">
> 
>                              <div class="capcha-wrapper" id="register-capcha">
>                                         <input type="text" v-model="inputValue" />
>                                         <supercapch
>                                         :value="inputValue"
>                                         @getCode="getCaptchaCode"
>                                         @isValid="checkValidCaptcha"
>                                         />
>                                 </div>
> 
>     <script type="application/javascript">
>             const registerCapcha = {
>                 data: function() {
>                     return {}
>                 },
>                 methods: {},
>                 components: {
>                     "supercapch": VueClientRecaptcha
>                 },
>                 setup() {
>                     var inputValue = null;
> 
>                     var getCaptchaCode = function getCaptchaCode(value) {
>                         console.log(value);
>                     };
>                     var checkValidCaptcha = function checkValidCaptcha(value) {
>                         console.log(value);
>                     };
>                     return {
>                         inputValue,
>                         getCaptchaCode,
>                         checkValidCaptcha,
>                     };
>                 }
>             };
>             Vue.createApp(registerCapcha).use(store).mount('#register-capcha');
>     </script>
> ```
> 
> Which sadly ends up with ": e.useSlots is not a function" error, couldnt find any example on how to get it working in this way, using vue3

**Comment by parsajiravand** [comment]
> Hello, I tried to do inline install , is that possible ?
> 
> I tried it like this:
> 
> ```
> <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/vue-client-recaptcha.umd.js"></script>
> <link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/style.css">
> 
>                              <div class="capcha-wrapper" id="register-capcha">
>                                         <input type="text" v-model="inputValue" />
>                                         <supercapch
>                                         :value="inputValue"
>                                         @getCode="getCaptchaCode"
>                                         @isValid="checkValidCaptcha"
>                                         />
>                                 </div>
> 
>     <script type="application/javascript">
>             const registerCapcha = {
>                 data: function() {
>                     return {}
>                 },
>                 methods: {},
>                 components: {
>                     "supercapch": VueClientRecaptcha
>                 },
>                 setup() {
>                     var inputValue = null;
> 
>                     var getCaptchaCode = function getCaptchaCode(value) {
>                         console.log(value);
>                     };
>                     var checkValidCaptcha = function checkValidCaptcha(value) {
>                         console.log(value);
>                     };
>                     return {
>                         inputValue,
>                         getCaptchaCode,
>                         checkValidCaptcha,
>                     };
>                 }
>             };
>             Vue.createApp(registerCapcha).use(store).mount('#register-capcha');
>     </script>
> ```
> 
> Which sadly ends up with ": e.useSlots is not a function" error, couldnt find any example on how to get it working in this way, using vue3

Thank you very much for the report you gave. Today I am working on a new version to which a cdn will be added with a new rollup configuration.

**Comment by parsajiravand** [comment]
@Songoo7 
### You can import recaptcha as module
`<link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/style.css">
<script type="importmap">
  {
    "imports": {
      "vue": "https://unpkg.com/vue@3/dist/vue.esm-browser.js"
    }
  }
</script>
<div class="capcha-wrapper" id="register-capcha">
    <input type="text" v-model="inputValue" />
    <supercapch :value="inputValue" @get-code="getCaptchaCode" @is-valid="checkValidCaptcha" />
</div>

<script type="module">
    import { createApp } from 'vue'
    import VueClientRecaptcha from "https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.1/dist/vue-client-recaptcha.es.js"
    const registerCapcha = {
        data: function ()
        {
            return {}
        },
        methods: {},
        components: {
            "supercapch": VueClientRecaptcha
        },
        setup()
        {
            var inputValue = null;

            var getCaptchaCode = function getCaptchaCode(value)
            {
                console.log(value);
            };
            var checkValidCaptcha = function checkValidCaptcha(value)
            {
                console.log(value);
            };
            return {
                inputValue,
                getCaptchaCode,
                checkValidCaptcha,
            };
        }
    };
    createApp(registerCapcha).mount('#register-capcha');
</script>`

**Comment by Songoo7** [comment]
Hello, ty for answer, will try to think it out some way, importmap is not well supported in browsers, but may be workaround with using https://github.com/guybedford/es-module-shims , although not sure what would happen to rest of my app which is done in classic cdn way, so guess will have to somehow rework it all or dunno :--)

**Comment by parsajiravand** [comment]
> Hello, ty for answer, will try to think it out some way, importmap is not well supported in browsers, but may be workaround with using https://github.com/guybedford/es-module-shims , although not sure what would happen to rest of my app which is done in classic cdn way, so guess will have to somehow rework it all or dunno :--)

**Hi Songoo **
### If you one use with classic cdn easyli copy this code then remove vue and add your functions (I removed store you can add it again)
@Songoo7 

```
<script src="https://unpkg.com/vue@3"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.3"></script>
<link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.3/dist/style.css">

<div class="capcha-wrapper" id="register-capcha">
    <input type="text" v-model="inputValue" />
    <supercapch :value="inputValue" @get-code="getCaptchaCode" @is-valid="checkValidCaptcha" />
</div>

<script type="application/javascript">
    const registerCapcha = {
        data: function ()
        {
            return {}
        },
        methods: {},
        components: {
            "supercapch": VueClientRecaptcha
        },
        setup()
        {
            var inputValue = null;

            var getCaptchaCode = function getCaptchaCode(value)
            {
                console.log(value);
            };
            var checkValidCaptcha = function checkValidCaptcha(value)
            {
                console.log(value);
            };
            return {
                inputValue,
                getCaptchaCode,
                checkValidCaptcha,
            };
        }
    };
    Vue.createApp(registerCapcha).mount('#register-capcha');
</script>
```

**Comment by Songoo7** [comment]
Tnx very much, worked :P - https://i.imgur.com/SwttgEb.png

Had to change from @getCode to @get-code for some reason.
Was a bit confused from "setup" method so changed it to oldchool, I just love simple things :)

Again tnx much for help!!

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.3"></script>
<link rel="stylesheet" media="screen" href="https://cdn.jsdelivr.net/npm/vue-client-recaptcha@1.0.3/dist/style.css">
			
<supercapch
:value="inputValue"
@get-code="getCaptchaCode"
@is-valid="checkValidCaptcha"
></supercapch>

<button v-if="showSubmit" type="button">
	Code OK, submit form.
</button>

<script type="application/javascript">

		const registerCapcha = {
			data: function() {
				return {
					inputValue: null,
					showSubmit: false
				}
			},
			methods: {
				getCaptchaCode(value) {
					//console.log(value);
				},
				checkValidCaptcha(value) {
					if(value === true) {
						this.showSubmit = true;
					}
				}
			},
			components: {
				"supercapch": VueClientRecaptcha
			}
		};
		Vue.createApp(registerCapcha).use(store).mount('#register-capcha');

</script>

```
