### ISSUE TITLE
Cannot get return value.

### ISSUE THREAD

**Issue by okywijaya** [parsajiravand/vue-client-recaptcha#9]
Thank you, for your tutorial.
But I get problem cannot get the return value from checkValidCaptha. I need the return value for methods button @click.

**Comment by parsajiravand** [comment]
### Hi my freind 

I create sample with Option API and Compositon API in vue3 you can see and simply just call getCodeFunction.
**if still you  have problem please share your code here .**
https://codesandbox.io/s/sample-get-code-vue-client-recaptcha-k19kks

**Comment by okywijaya** [comment]
This is my simple code :

![image](https://user-images.githubusercontent.com/47132213/188272344-b2387b17-8229-4596-a0ff-fee504b271ca.png)

![image](https://user-images.githubusercontent.com/47132213/188272394-8ead2f30-99eb-48ae-b8ba-df32caacd197.png)

**Comment by alirezamosadeghseo** [comment]
گیت هاب رویت شد .

**Comment by parsajiravand** [comment]
your problem is usign OptionAPI and ComositionAPI together, **you can,t access setup functions in your methods with THIS**
please send code in  .vue file i fixing your problem

@okywijaya

**Comment by okywijaya** [comment]
This is my simple code Sir @parsajiravand,

<template>
  <div>
    <div class="row">
            <div class="col-md-6 left-box">
                <VueClientRecaptcha
                  :value="inputValue"
                  :hideLines="true"
                  :show-capital-case-letters="false"
                  :show-lower-case-letters="false"
                  custom-text-color="black"
                  @getCode="getCaptchaCode"
                  @isValid="checkValidCaptcha"
                  v-model="capthaResult"
                >
                  <template #icon>
                  <span style="color:blue">Reload Captcha</span> 
                    </template>
                </VueClientRecaptcha>
                <input type="text" v-model="inputValue" placeholder="masukan captha dengan benar!" />
            </div>
      </div>
      <div class="row">
              <div class="col-md-6 left-box">
                <input
                  type="button"
                  value="Save Data"
                  class="btn btn-primary"
                  @click="save()"/>
              </div>
            </div>
  </div>
</template>
<script>
import VueClientRecaptcha from "vue-client-recaptcha";
import { ref } from "vue";

export default {
  components: {
     VueClientRecaptcha,
  },
  setup() {
    /* pass value to captcha  */
    const inputValue = ref(null);

    const getCaptchaCode = (capthaResult) => {
      /* you can access captcha code */
      console.log(capthaResult);
    };
    const checkValidCaptcha = (capthaResult) => {
      /* expected return boolean if your value and captcha code are same return True otherwise return False */
      console.log("this is captha valid " + capthaResult);
    };
    
    return {
      inputValue,
      getCaptchaCode,
      checkValidCaptcha,
    };
  },
  data: function () {
    return {
      capthaResult : null
    };
  },
  methods: {
    save() {
      console.log("this is from click " + this.capthaResult);
    },
  },
};
</script>

**Comment by parsajiravand** [comment]
### This code is currect you can copy
@okywijaya 
#https://codesandbox.io/s/sample-get-code-vue-client-recaptcha-k19kks?file=/src/components/SampleOnSaveWithOptionAPI.vue

**Comment by okywijaya** [comment]
Alhamdulillah, Jazakallahu khair Sir @parsajiravand. 
May Allah Subhanahu Wa Taala, revenge you with alot of goodnes.
